version: "3.8"

services:
  www_redis_normal:
    image: redis:alpine
    container_name: www_redis_normal_01
    restart: always
    networks:
      - webnet
networks:
  webnet:
    name: webnet
    driver: bridge
